# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moldyreviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie_rating',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
