# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moldyreviews', '0002_auto_20161128_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie_title',
            field=models.CharField(max_length=200),
        ),
    ]
